#credenciales
browserstack.username=
browserstack.access_key=

#configuramos el entorno de ejecucion en BrowserStack
browserstack.browser.name=Chrome
browserstack.browser.version=latest
browserstack.os.name=Windows
browserstack.os.version=11

#se llaman los metodos para ordenar el rastro de ejecucion
browserstack.project.name=Scotia Automation Mobile
browserstack.build.name=Marketplace Multiplatform
browserstack.session.name=Test Session
browserstack.local=false

#las opciones de depuracion y logs remotos
browserstack.debug=false
browserstack.network.logs=false

#configuracion movil BrowserStack
browserstack.mobile.android.device.name=Samsung Galaxy S24
browserstack.mobile.android.os.version=14.0
browserstack.mobile.android.browser.name=Chrome
browserstack.mobile.ios.device.name=iPhone 15
browserstack.mobile.ios.os.version=17.0
browserstack.mobile.ios.browser.name=Safari
