# Plataforma
platform=android

# Dispositivo
deviceName=Android Emulator

# Versión Android
platformVersion=17

# Automatización
automationName=UiAutomator2

# Appium
appiumServer=http://127.0.0.1:4723

# BrowserStack
browserstack=false